ProjetoRails/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'home/index'
  root "home#index"
  devise_for :users
  resources :posts do
    resources :comments
  end

  root "posts#index"

  resources :posts
  root "posts#index"

  get 'about' => 'home#about', as: 'about'
end

ProjetoRails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ProjetoRails/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

ProjetoRails/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments , dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true
end

ProjetoRails/app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

ProjetoRails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


end

ProjetoRails/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name,:body))
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end

end

ProjetoRails/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

ProjetoRails/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all.order('created_at DESC' )
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to @post
    else
    render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    @post.save

    redirect_to posts_path
  end
  def show
    @post = Post.find(params[:id])
  end

  private
    def post_params
      params.require(:post).permit(:title, :body)
    end

end

ProjetoRails/app/helpers/application_helper.rb
module ApplicationHelper
end

ProjetoRails/app/helpers/comments_helper.rb
module CommentsHelper
end

ProjetoRails/app/helpers/home_helper.rb
module HomeHelper
end

ProjetoRails/app/helpers/posts_helper.rb
module PostsHelper
end

ProjetoRails/app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>

  <p>
    <%= f.text_area :body %>
  </p>
  <br>

  <p>
    <%= f.submit %>

<% end %>

ProjetoRails/app/views/comments/comments.html.erb
<div class="comment clearfix">
  <div class="comment_content">
    <p class="comment_name"><strong><%= comment.name %></strong></p>
    <p class="comment_body"><%= comment.body %></p>
    <p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago </p>
  </div>

  <p><%= link_to 'Deletar', [comment.post, comment],
                  method: :delete,
                  class: "button",
                  data: {confirm: 'Tem certeza?'} %>

  </p>
</div>

ProjetoRails/app/views/home/about.html.erb
<style>
  .espaco{
    padding: 20px;
  }
  </style>
  <title>Sobre</title>
  <div class="espaco">
<center><p class ="mb-5">Bem vindo ao All for All, esse site tem como objetivo ser um espaço onde as pessoas possam expressar seus sentimentos sem medo pois será feito tudo "anonimamente", desde que não ofendam os outros membros, além disso você pode compartilhar situações que você acha que podem incentivar,motivar, ou até mesmo fazer com que a pessoa se sinta melhor.<br>
As vezes apenas uma palavra amiga, não é o necessário para se sentir melhor, e para isso recomendamos que a pessoa se dirija a um profissional, pois não podemos deixar que a tristeza nos siga para tudo que é lugar.</p>

<b>Segue abaixo o telefone de alguns psicologos gratuitos disponiveis no DF</b>
<br><br>

<div class="row">
  <div class="col-sm-3">
    <div class="card" style="width: 18rem; height:15rem">
      <div class="card-body">
        <h5 class="card-title">Universidade de Brasilia</h5>

        <p class="card-text">Inscrições abertas uma vez por semestre no Instituto de Psicologia. Interessados devem manter contato para saber saber quando as vagas estarão disponíveis.</p>
      </div>
    </div>
  </div>
  <div class="col-sm-3">
    <div class="card" style="width: 18rem; height:15rem">
      <div class="card-body">
        <h5 class="card-title">Universidade Católica</h5>
        <p class="card-text">Horário: segunda a sexta, das 8h às 22h; sábado, das 8h às 12h</p>
          Telefone: (61) 3356-9000</p>
      </div>
    </div>
  </div>



  <div class="col-sm-3">
    <div class="card" style="width: 18rem; height:15rem">
      <div class="card-body">
      <h5 class="card-title">Uniceub</h5>
        <p class="card-text">Horário: segunda a sexta, das 8h às 22h; sábado, das 8h às 12h<br>
    Telefone: (61) 3356-9000</p>

      </div>
    </div>
  </div>
  <div class="col-sm-3">
    <div class="card" style="width: 18rem; height:15rem">
      <div class="card-body">
        <h5 class="card-title">IESB</h5>
        <p class="card-text">Horário: segunda a sexta, das 7h30 às 21h; sábado, das 8h às 13h<br>   Telefone: (61) 3445-4502</p>
      </div>
    </div>
  </div>
</div>
</div>
</center>

ProjetoRails/app/views/home/index.html.erb
<title>All for All</title>

<body bgcolor='FFFF00'>
    <br><br>
    <center>
    <img src="https://image.flaticon.com/icons/svg/478/478533.svg" width=20% height=20%>
    <br><br>
    <%if Post.count>0 %>
    <div class="card text-center" style="width: 18rem;" >
      <div class="card-body">
        <h5 class="card-title">Ultimo Post do Site</h5>
        <h6 class="card-subtitle mb-2 text-muted"><%=Post.all.last.title%></h6>
        <p class="card-text"><%=Post.all.last.body.lines.first%>...</p>
        <a href='/posts/<%=Post.all.count.to_s%>' class="btn btn-primary">Ler Completo</a>
      </div>
    </div>
    <% else %>
    <div class="card text-center" style="width: 18rem;" >
      <div class="card-body">
        <h5 class="card-title">Ultimo Post do Site</h5>
        <h6 class="card-subtitle mb-2 text-muted">Não há posts</h6>
        <p class="card-text">Nada a mostrar...</p>
      </div>
    </div>
    <% end %>
    </center>
</body>

ProjetoRails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<style>
.right{
  padding-right:100px;
}
</style>
<html>
  <head>
  <link rel="shortcut icon" href="<%=image_url("icon.ico")%>"/>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

 <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/" style="font-size:30px; font-family: 'Times New Roman', Helvetica, sans-serif; font-style: italic">All for All</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/">Inicio <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/posts">Posts</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/about" >Sobre</a>
      </li>
</ul>
  </div>
    
</nav>
<div class="right">
<p style="text-align:right;font-size:20px">
  <%if user_signed_in?%>
  <%= link_to 'Sair', destroy_user_session_path, 
       method: :delete %>
  <%else %>
  <%= link_to('Entrar', new_user_session_path)  %>  
  <%= link_to('Registrar', new_user_registration_path)  %>

  <%end%>
   </p>
    <%= yield %>
</div>
  </body>
</html>

ProjetoRails/app/views/posts/_form.html.erb
  <%= form_for @post do |f| %>
  <%if @post.errors.any? %>
  <div id="errors">
    <h2><%= pluralize(@post.errors.count, "erro")%> estão impedindo este post de ser salvo   </h2>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :titulo %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :conteúdo %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>
  <% end %>

ProjetoRails/app/views/posts/edit.html.erb
<title>Editar Post</title>
<div id="post_wrapper">
  <h1>Editar post</h1>
   <%= render 'form'%>
</div>

ProjetoRails/app/views/posts/index.html.erb
<style>
    .ali{
        padding-left:20px;
    }
</style>
<title> Posts</title>
<div class="ali">
<% if user_signed_in? %>
<a class="btn btn-primary" href="/posts/new" role="button">Novo Post</a><br><br>
<h2 class="title"> Posts no blog</h2>
<% @posts.each do |post| %>
  <div class="row">

    <div class="card text-center" style="width: 25rem; height:20rem" >
  <div class="card-header" style="text-transform:uppercase">
    <b>Post <%=post.id%></b>
  </div>
  <div class="card-body">
    <h5 class="card-title" style="text-transform:uppercase"><%= post.title %></h5>
    <p class="card-text"><%=post.body.lines.first%>...</p>
    <b>Texto completo em:</b> <%= link_to post.title, post %>
  </div>
  <div class="card-footer text-muted">
    <p class="date"><%= post.created_at.strftime("%B, %d, %Y") %></p>
  </div>
</div>
  
<%end%>
</div>
</div>
</div>
<br>
<p>

</p>


<%if Post.count==0%>
<center>
  <p> Não há posts disponiveis para a vizualização.</p>
</center>
<%end%>
<%else%>
  <center>
    <p>Você não está conectado, conecte-se ou registre-se para vizualizar os posts de outros usuarios.</p>
  </center>
<%end%>
<div>
  <% flash.each do |name,msg| %>
    <%= content_tag(:div, msg, class: "alert") %>
  <% end %>
</div>

ProjetoRails/app/views/posts/new.html.erb
<title> Novo Post</title>
<style>
    .ali{
        padding-left:20px;
    }
</style>

<div class="ali" id="post_wrapper">
  <h1>Novo post</h1>
    <%= render 'form' %>
</div>

ProjetoRails/app/views/posts/show.html.erb
<title><%=@post.title%></title>
<style>
.padrao{
  padding-left: 30px;
}
</style>
<div class="padrao">
<%if user_signed_in?%>
<br>
<h3 class="title" style="text-transform: uppercase;"><b><%=@post.title%></b></h3>

<div class="card" style="width: 50rem;">
  <div class="card-body">
    
    <p class="card-text" style="text-align:left"><%= @post.body%></p>
    </div>
</div>

      <p class="date">
    Submitted <%= time_ago_in_words(@post.created_at) %> Ago
    <% if current_user == @post.user %>
    | <%= link_to 'Editar', edit_post_path(@post) %>
    | <%= link_to 'Deletar', post_path(@post), method: :delete, data: {confirm: 'Tem certeza?' } %>
    <% end %>
  </p>
         

  <div id="comments">
    <br><br><br>
    <h4><b>Comentários</b></h4>

    <% @post.comments.each do |comment| %>
    <h5>Comentario <%=comment.id%></h5>
    <h6><%= comment.body %></h6>
    <br>
    <% end %>

    <h4>Adicionar Comentario:</h4>
    <%= render "comments/form" %>
  </div>
</div>
<%end%>
</div>